rootProject.name = "springclaw"

include("springclaw-core")
include("springclaw-spring-boot")
include("springclaw-gateway")
include("springclaw-channels")
include("springclaw-channels-discord")
include("springclaw-channels-telegram")
include("springclaw-tui")
include("springclaw-tools")
include("springclaw-memory")
include("springclaw-samples:sample-basic")
include("springclaw-samples:sample-multi-agent")
include("springclaw-cli")
include("springclaw-samples:sample-cli")
